---

# dancer
- name: invite the dancers
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - dancer
  roles:
    - dancer

# music
- name: check config static
  hosts: localhost
  gather_facts: false
  tags:
    - music
  roles:
    - check_config_static

- name: check config node
  hosts: all
  gather_facts: false
  become: true
  tags:
    - music
  roles:
    - pre-ansible
#    - bootstrap

- name: check system
  become: yes
  become_method: sudo
  hosts: all
  any_errors_fatal: true
  tags:
    - music
  roles:
    - check_system_static

- name: open the music
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - music
  roles:
    - music

# show_time
- name: deploy main directory
  gather_facts: false
  any_errors_fatal: true
  hosts: servers
  tags:
    - show
  tasks:
    - name: mkdir
      file: name={{ deploy_dir }} state=directory mode=755

# temporarily offline
#- name: deploy database-pre
#  become: yes
#  become_method: sudo
#  gather_facts: false
#  any_errors_fatal: true
#  hosts: db_servers
#  tags:
#    - db-pre
#  tasks:
#    - name: install packages required by database
#      yum:
#        name:
#          - net-tools
#          - bash-completion
#          - gcc
#          - unzip
#          - perl-Data-Dumper
#          - libaio-devel
#        state: latest
#      async: 90

- name: deploy db
  become: yes
  become_method: sudo
  gather_facts: false
  any_errors_fatal: true
  hosts: db_servers
  tags:
    - database
  roles:
    - database

# Temporarily offline
#- name : deploy nginx-pre
#  become: yes
#  become_method: sudo
#  gather_facts: false
#  any_errors_fatal: true
#  hosts: nginx_servers
#  tags:
#    - nginx-pre
#  tasks:
#    - name: install packages required by nginx
#      yum:
#        name:
#          - cmake
#          - openssl
#          - openssl-devel
#          - pcre
#          - pcre-devel
#          - zlib
#          - zlib-devel
#          - gd-devel
#          - libxml2-devel
#        state: latest
#      async: 90

- name: deploy nginx
  become: yes
  become_method: sudo
  gather_facts: false
  any_errors_fatal: true
  hosts: nginx_servers
  tags:
    - nginx
  roles:
    - nginx

- name: deploy jdk
  gather_facts: false
  any_errors_fatal: true
  hosts: servers
  tags:
    - jdk
  roles:
    - jdk

- name: deploy zookeeper
  gather_facts: false
  any_errors_fatal: true
  hosts: servers
  tags:
    - zookeeper
  roles:
    - zookeeper

- name: deploy ds-backend
  gather_facts: false
  any_errors_fatal: true
  hosts: servers
  tags:
    - backend
  roles:
    - backend

- name: initialize ds-backend database
  gather_facts: false
  any_errors_fatal: true
  hosts: db_servers
  tags:
    - backend_db
  roles:
    - backend_db

- name: deploy ds-frontend
  become: yes
  become_method: sudo
  gather_facts: false
  any_errors_fatal: true
  hosts: nginx_servers
  tags:
    - frontend
  roles:
    - frontend